### ISSUE TITLE
Support more models locally

### ISSUE THREAD

**Issue by Ar57m** [ShiftHackZ/Stable-Diffusion-Android#109]
have you considered supporting [segmind](https://huggingface.co/segmind) models, they have some small(and tiny) sd and sdxl models that seem to be decent. 🙏

**Comment by ShiftHackZ** [comment]
Seems like segmind models that you proposed are bundled as **safetensors** model, but implementation in SDAI app can only work with **ort** models, because android phones don't have enough resources to run safetensors model.

For example, here is uNet bundle of your model:

![image](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/41302477/7551ad0f-cae1-43f3-9fd7-e6240b1ab7fa)

And here is uNet bundle of model that is currently used in app:

![image](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/41302477/c05af7e6-65be-4173-936d-9ddd02b37bff)

You can try requesting the model author to bundle it as ort (or try converting it yourself), and try to use it after next 0.5.4 release will be available. (Now i'm still working on support multiple ort models: https://github.com/ShiftHackZ/Stable-Diffusion-Android/pull/107)

**Comment by Ar57m** [comment]
> Seems like segmind models that you proposed are bundled as **safetensors** model, but implementation in SDAI app can only work with **ort** models, because android phones don't have enough resources to run safetensors model.
> 
> For example, here is uNet bundle of your model:
> 
> ![image](https://private-user-images.githubusercontent.com/41302477/293913531-7551ad0f-cae1-43f3-9fd7-e6240b1ab7fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTI3OTgsIm5iZiI6MTcwNDMxMjQ5OCwicGF0aCI6Ii80MTMwMjQ3Ny8yOTM5MTM1MzEtNzU1MWFkMGYtY2FlMS00M2YzLTlmZDctZTYyNDBiMWFiN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMjFjN2FlMzA1MmI2Yzk2ZTFhOWNmNWM1YmU5M2ZmZGQ3NjhmMDc0N2Q5NmNiMGMyZjI2OWUwZDliNDk1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dheSYOgDtwwfWzvkoqm9sQ4TyoSEKxhbgRcXiJBDNk)
> 
> And here is uNet bundle of model that is currently used in app:
> 
> ![image](https://private-user-images.githubusercontent.com/41302477/293913720-c05af7e6-65be-4173-936d-9ddd02b37bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTI3OTgsIm5iZiI6MTcwNDMxMjQ5OCwicGF0aCI6Ii80MTMwMjQ3Ny8yOTM5MTM3MjAtYzA1YWY3ZTYtNjViZS00MTczLTkzNmQtOWRkZDAyYjM3YmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIwMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZWUxZGNhYjQzY2YwZDg3OTMxNmVhZDdiZjQ5YzEzYjI5NzIxMmE0NGJjYjNhZDM5NWFiNTI4NTUwNDg3NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NM86BiUUsbktpDpZiAlQKnNJmy_BvdDq-SCO-MoV6Zs)
> 
> You can try requesting the model author to bundle it as ort (or try converting it yourself), and try to use it after next 0.5.4 release will be available. (Now i'm still working on support multiple ort models: #107)

thanks for your work.
I trying to convert this
https://huggingface.co/akameswa/lcm-tiny-sd-onnx-fp16

but I got this error
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Failed to find kernel for BiasSplitGelu(1) (node BiasSplitGelu_0). Kernel not found

**Comment by Ar57m** [comment]
hey @ShiftHackZ thanks for the updates now with the new version I click on Local, but nothing happens, I can't generate anything

**Comment by Ar57m** [comment]
> hey @ShiftHackZ thanks for the updates now with the new version I click on Local, but nothing happens, I can't generate anything

opened an issue, will close this
