### ISSUE TITLE
Gallery not always visible

### ISSUE THREAD

**Issue by lead0r** [ShiftHackZ/Stable-Diffusion-Android#48]
Thanks for the great work. I hope in the future the API will support more features.
I can successfully generate images, but even with "always save images" activated, they are only visible in the app gallery and I have to manually save them in the phone gallery. Is it possible to automatically save them there?
My problem is, that after a while, the app gallery is not visible anymore and then I have no access to the generated images at all. Screenshot of the app gallery showing the problem
![Screenshot_2023-05-28-16-11-14-441_com.shifthackz.aisdv1.app.jpg](https://github.com/ShiftHackZ/Stable-Diffusion-Android/assets/15450754/79cc212a-90b9-4b60-bab9-766364e87eea)

**Comment by ShiftHackZ** [comment]
Hi @lead0r, thanks for telling about the issue.

The images are stored in local SQL-based DB as base64 string (not as actual file), so it is likely that some base64 reached the max limit, and there is an exception occurring while gallery loading and trying to convert that broken base64 to bitmap.

I think it can be fixed in converter not to process bad base64.

By the way, do you remember what image sizes you had in your gallery? Are there any images that are significantly large (like 2048x2048) ?

**Comment by lead0r** [comment]
I don't remember, but that is very much likely, yes

**Comment by astravexton** [comment]
Sorry to reply on this issue, but is there a way to export the SQL database? There are some images I've generated but can't view in the gallery as it only lets me scroll back around 20 images before it just stops. On version 0.5.2 (165)
