### ISSUE TITLE
Request: Improvement of saving images in local Gallery

### ISSUE THREAD

**Issue by Azathoth88** [ShiftHackZ/Stable-Diffusion-Android#53]
User Story:
As a user, I would like to be able to access the images in my local image gallery. 

- The images should be automatically saved in a desired directory
- Alternatively I would like to save the image with one (!) click into a directory
- Ideally the path can be configured in the settings

To the background: The pictures are stored at present apparently in a local data base?! (I could not find the images in the Android file system).
The share function works - BUT: It's just too many clicks to save a picture to the phone. 
So, in addition to the share function, another "Save" button would be useful here.

**Comment by ShiftHackZ** [comment]
Hello, thanks for your feature proposal! 

For now I see the implementation possible this way:

- Since Android 12L (API 32) google restricts for apps to work with external storage directly, so selecting desired folder is not possible on newest OS versions. As I want UX not to be fragmented depending on OS, it can be saved automatically in Downloads/SDAI folder. 

- Saving to storage will be performed only if user granted permissions and enabled "Save to Downloads' in settings. If permissions granted on first app launch - setting is enabled by default. Although, this settings won't affect "Share" function in gallery.

- Auto saving will be performed automatically if "Auto save" and "Save to Downloads" is enabled in settings. If "Auto save" is disabled and "Save to Downloads" enabled, image will be saved depending on user decision in result dialog.

- Sharing function in gallery works as "Intent", so amount of clicks is defined by how many apps that can accept that image you have installed in your system, even file managers (like Total Commander) can allow you to save it as file, so I think no changes in flow needed here.


There is an experimental branch with implementation, available here: https://github.com/ShiftHackZ/Stable-Diffusion-Android/pull/61
if you want to try it before feature will be included in some of next releases, you can build it.
