### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by shufuwa** [ShiftHackZ/Stable-Diffusion-Android#89]
**Describe the bug**
When I try to access sd through the app it results in a 500 Internal server error while it works if i go to my servers ip

**To Reproduce**
1. run `./webui.sh --use-cpu all --precision full --no-half --skip-torch-cuda-test --api --listen`
2. enter server ip with port in the app and click connect
3. 500 internal server error with the following error output ``` [output.txt](https://github.com/ShiftHackZ/Stable-Diffusion-Android/files/12472939/output.txt)

**Expected behavior**
To be connected without errors

**Desktop (please complete the following information):**
 - desktop/server: Linux 6.4.7-zen1-3-zen (arch linux)

**Smartphone (please complete the following information):**
 - Device: Moto G13
 - OS: Android 13
 - Browser Latest Bromite/Firefox worked by going to server ip

**Comment by ShiftHackZ** [comment]
According to your output.txt your problem is also connected to api bug with sd_model_checkpoint variable.

Here is similar issue in this repo: https://github.com/ShiftHackZ/Stable-Diffusion-Android/issues/87

But the main issue is connected to API bug, and not the SDAI app, it is opened in A1111 repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9013

**Comment by ShiftHackZ** [comment]
By the way, what exact action in the app produces the 500 resoponse ? Is it server setup screen, or it happens for you on image generation ?
